name: Python application test

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ 3.11 ]  # Specify the version of Python you want to use

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Add project directory to PYTHONPATH
        run: echo "PYTHONPATH=\$PYTHONPATH:${{ github.workspace }}" >> $GITHUB_ENV
      - name: Run tests with coverage
        run: |
          coverage run -m pytest -s -v
          coverage report
          coverage xml  # Optional: Generate an XML report for use with other tools
